### ISSUE TITLE
面向金融领域的事件因果关系抽取数据集问题

### ISSUE THREAD

**Issue by ZYMblog** [10jqka-aicubes/causality_extraction_demo#2]
您好，请问可以分享一下 同花顺 竞赛官网的数据集吗？

**Comment by YangLock** [comment]
官网的报名结束了，数据集没法下载，方便分享一下数据集吗？

**Comment by Tsukiaa** [comment]
请问大家谁有数据集呀？可以分享一下吗？

**Comment by ZYMblog** [comment]
请问您也做因果关系相关的研究吗，方便加个好友进一步交流一下吗

Tsukiaa ***@***.***> 于2023年2月2日周四 18:28写道：

**Comment by 10jqka-aicubes** [comment]
@ZYMblog @YangLock @Tsukiaa 数据集已开放下载

**Comment by ahao0328** [comment]
谁有数据集呀，方便提供一份吗？现在下载不了了

**Comment by zengzhixian1995** [comment]
谁有数据集呀，方便分享一份吗？
